title: Tom Ootes
description: Tom Ootes is een geÃ«ngageerde software-developer, werkzaam voor de Nederlandse overheid.
author: Tom Ootes
email:  tom@ootes.io
baseurl: ""
url: "http://example.com"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _scss
exclude:
  - "/node_modules"
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - _sass
  - _posts
  - css
  - js

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  talks:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: talks
    values:
      layout: talk